### ISSUE TITLE
March 1, 2016 (this is a Tuesday!)

### ISSUE THREAD

**Issue by roughani** [code4sac/meetups#7]
- [x] Assign responsible Core Team member
- [x] Confirm location
- [x] Recruit speaker(s) or develop 30-45 minutes of content
- [x] Draft meetup title and description
- [x] Post and announce on [meetup.com](http://www.meetup.com/Code4Sac/) one week in advance
- [ ] Market and promote event via email blasts (monthly), social media, announcements at other meetups, personalized outreach to stakeholders, etc.
- [ ] Create slide deck to structure meetup experience
- [ ] Set up space 30 minutes prior to event (and recruit help if necessary)

**Comment by roughani** [comment]
@joelrip correct me if I'm wrong, but we're going to co-organize the Hack4Sac event on Tuesday, March 1 in lieu of a Wednesday meetup? 

Registration link:
https://www.eventbrite.com/e/hack4sac-kickoff-event-registration-21014497929

County News Release:
http://www.saccounty.net/news/latest-news/Pages/Be-the-Solution-Hack4Sac-Civic-Tech-Challenge.aspx

**Comment by joelrip** [comment]
@roughani That's my understanding.
